### ISSUE TITLE
🔥 TODO Лист - Основы работы с данными ( 57 урок)

### ISSUE THREAD

**Issue by DenUP** [DenUP/First_APP#9]
### **Общее:**

1. Повторить самому иногда подглядывая
2. Создать репозитории и сделать самостоятельно

- lib
- - widgets
- - - groups
- - - - groups_widget.dart - экран группы
- - - - group_widget_midel.dart - будут лежать данные\
- - - app
- - - - my_app.dart

### Часть А

**My_app** - инициализируем роутеры, прописываем цвет темы

_"/groups"_ - главный экран 

### **Groups_widget**

- [x] **"STL" GroupsWidget** ( главный экран)
- [x] **"STL" _GroupsListWidget** => ListView.separated
- [x] **"STL" _GroupsListRowWidget** => ListTitle

Добавляем indexList - чтобы знать какие индексы передавать 

- [x] **GroupsWidget => FloatingActionButton**

### Часть B

Добавляем свайп в лист:

- [x] Подключаем библиотеку flutter_sidable
- [x] Оборачиваем наш ListTitle в Slidable
- [x] Добавляем **actionPane(ibehind)** - это как будет слайдиться
- [x] Добавляем action
- [x] Оборачиваем в widgetColor (ListTitle)
- [x] Добавить (клик) onTap в ListTitle

### Часть C ( Экран добавление группы)

- lib
- - widgets
- - - group_form
- - - - groups_form_widget.dart - экран 
- - - - group_form_widget_model.dart - будут лежать данные\

- [x] **"STL" GroupsFormWidget** ( главный экран)
- [x] Добавляем его в роутер "/groups/form"
- [x] Добавляем appBar

#### Groups_widget.dart

- [x] Добавляем функцию (void showFrom) с Context
- [x] добавляем навигатор
- [x] вставляем эту функцию в кнопку "снизу"

#### GroupFormWidget

- [x] **"STL" GroupNameWidget**
- [x] Добавляем TextField и декорируем
- [x] Добавляем hitnText и аутофокус
- [x] Добавляем floatingActionButton

#### group_form_widget_model.dart

- [x] class GroupFormWidgetModel
- [x] GroupFormWidgetModelProvider ( InheritedNotif)
- [x] В провайдер добавить модель

#### group_form_widget.dart

- [x] **"STL" _GroupFormWidgetBody**
- [x] Переносим в нее всю верстку

- [x] ** GroupFormWidget** - Делаем STF
- [x] прописываем _модель
- [x] Заворачиваем в провайдер, прописываем модель

### Часть Е

- [x] В нашей модели добавляем функцию saveGroup
- [x] Нашу кнопку в **FormWidget** добавляем ModelProvider.read......saveGroup

- [x] В модели добавляем переменную GroupName = ''
- [x]  В TextField добавляем onEditionComplite -> saveGroup
- [x]  В TextField добавляем onChanged: model?groupName=value
- [x] В saveGroup - выходные данные BuildContext

### Часть F - Работа с данными

- [x] Инициализируем Hive
- [x] Добавим WidgetFlutterBilding... (main.dart)
- [x] добавим Have.init...

- lib
- - domain
- - - entity
- - - - group.dart

#### group.dart

- [x] class Group
- [x] String name
- [x] генерируем адаптер ( build )

#### Group_form_widget_model.dart

- [x] В функции проверяем, если groupname пустой, то return
- [x] Дальше открываем бокс, тип выставляем (Final box)
- [x] Final group = передаем значение groupName в Group
- [x] в box добавляем нашу group
- [x] Если наш адаптер не зареган, то регаем
- [x] После вызыва, происходит POP

### Часть G

- [x] class GroupsWidgetModel (ChangeNotifier)
- [x] GroupsWidgetModelProvider (InheritedNotifier)
- [x] Указываем модуль

#### groups_widget.dart

- [ ] **"STL" _GroupFormWidgetBody** (переносим верстку)
- [ ] GroupsWidget => STF
- [ ] Добавляем модель
- [ ] Оборачиваю провайдер, добавляю модель
- [ ] Из Groups_widget (showFrom) -> model переносим
- [ ] Изменяем onPresed -> обращаемся к модели

#### Class GroupWidgetModel

- [ ] Добавляем переменную _group (Тип Group[ ]: )
- [ ] List<Group>get

#### Class GroupListWidget

- [ ] Добавляем переменную, которая будет следить за длинной группы, если null, то возвратит 0;
- [ ] Вставляем его в ItemCount

#### Group_Widget_model

- [ ] Добавляем функцию ( _setup )
- [ ] проверяем зарегистрирован ли адаптер
- [ ] открываем бокс
- [ ] в _groups добавляем values.toList()
- [ ] Затем обновляем наших слушателей
- [ ] box.listenable
- [ ]  _Setup добавляем в конструктор

#### GrouplistRowWidget

- [ ] **final model** - где будет читать модель групп [index]

**Comment by DenUP** [comment]
Ничего не понял, **а слепо следовать не хочется**. 

Поэтому на основе изображении, попробую сделать сам 

relax - https://www.youtube.com/watch?v=3US9x1fKqPw&list=RDMM&start_radio=1

**Comment by DenUP** [comment]
Все готово и загружено  ️️️😎 😏
